name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11.0.0 (or JAVA SE 11)
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew (chmod +x)
      run: cd MechanicalMustang && chmod +x gradlew
    - name: Build with Gradle (./gradlew build)
      run: cd MechanicalMustang && ./gradlew build && echo Done!
